development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: people_book_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDISTOGO_URL"] %>
  channel_prefix: people_book_production
