development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: people_book_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: people_book_test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: people_book_production
